markdown: rdiscount
permalink: /:title/
url: http://tonghaibo.github.com
name: lalahunter
author: kurapica
qq: 383062197
email: nihao292613@163.com
duoshuo: tony
beian: love
cnzz: 1257103637
weibo: 1240989305
github: tonghaibo
pygments: true
safe: true
paginate: 20
about: "这里是 kurapica 的个人博客，欢迎观赏、建议、拍砖……"
